[versions]
kotlin = "2.0.20"
android-gradle-plugin = "8.4.2"
androidTools = "31.6.0"

[libraries]
# Dependencies of the included build-logic
android-tools-build = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }


[plugins]
android-application = { id = "haitrvn.android.application" }
android-application-compose = { id = "haitrvn.android.application.compose" }
android-library = { id = "haitrvn.android.library" }
android-library-compose = { id = "haitrvn.android.library.compose" }
android-test = { id = "haitrvn.android.test" }
android-jacoco = { id = "haitrvn.android.jacoco" }
android-koin = { id = "haitrvn.android.koin" }
android-lint = { id = "haitrvn.android.lint" }
library-jvm = { id = "haitrvn.library.jvm" }
library-multiplatform = { id = "haitrvn.library.multiplatform" }
