[versions]
kotlin = "2.0.20"
android-gradle-plugin = "8.4.2"
androidTools = "31.6.0"

[libraries]
# Dependencies of the included build-logic
android-tools-build = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }


[plugins]
feature-common = { id = "haitrvn.android.application" }